USE [GD1C2014]
GO
DROP TABLE DATA_GROUP.FuncionalidadXRol
GO
DROP TABLE DATA_GROUP.UsuarioXRol 
GO
DROP TABLE DATA_GROUP.CalificacionPublicacion 
GO
DROP TABLE DATA_GROUP.Compra 
GO
DROP TABLE DATA_GROUP.Oferta 
GO 
DROP TABLE DATA_GROUP.ItemFactura 
GO
DROP TABLE DATA_GROUP.Factura 
GO
DROP TABLE DATA_GROUP.Pregunta 
GO
DROP TABLE DATA_GROUP.Publicacion 
GO
DROP TABLE DATA_GROUP.Rol 
GO
DROP TABLE DATA_GROUP.Funcionalidad 
GO
DROP TABLE DATA_GROUP.Administrador 
GO
DROP TABLE DATA_GROUP.Cliente 
GO
DROP TABLE DATA_GROUP.Empresa 
GO
DROP TABLE DATA_GROUP.Usuario 
GO
DROP TABLE DATA_GROUP.TipoDocumento 
GO
DROP TABLE DATA_GROUP.Rubro 
GO
DROP TABLE DATA_GROUP.TipoPublicacion 
GO
DROP TABLE DATA_GROUP.VisibilidadPublicacion 
GO
DROP TABLE DATA_GROUP.EstadoPublicacion 
GO
DROP SCHEMA DATA_GROUP
GO



